"""
Generate simple EPW files per zone using future-period (2040-2069)
monthly climatology available in `results/statistics/monthly_climatology_future_2040_2069_ssp585.csv`.

This script creates one representative year (2045) with hourly rows where
values are built from monthly means with a simple diurnal cycle.

Usage:
	python scripts/epw_file_generator.py

Output:
	results/epw_future_2040_2069/<zone>.epw

Notes:
	- This creates a basic EPW formatted file with placeholder location
	  metadata. For higher-fidelity EPW files, provide hourly source
	  data (e.g. `results/climate_3h_all_zones.csv`) or supply site
	  coordinates.
"""

from pathlib import Path
import numpy as np
import pandas as pd
from datetime import datetime, timedelta


ROOT = Path(__file__).resolve().parents[1]
STATS = ROOT / "results" / "statistics" / "monthly_climatology_future_2040_2069_ssp585.csv"
OUTDIR = ROOT / "results" / "epw_future_2040_2069"


def specific_humidity_to_dewpoint(q, p=101325.0, T_c=20.0):
	# q: specific humidity (kg/kg), p: pressure Pa, T_c used if needed for sign
	# convert to vapour pressure e (Pa)
	# mixing ratio w = q / (1 - q)
	w = q / (1 - q + 1e-12)
	e = (w * p) / (0.622 + w)
	# avoid tiny/negative
	e = np.maximum(e, 0.1)
	# Magnus formula inverse to get dew point in C
	ln_ratio = np.log(e / 611.2)
	Td = (243.04 * ln_ratio) / (17.625 - ln_ratio)
	return Td


def make_hourly_series_for_zone(zone_df):
	# zone_df has rows month (1-12) and columns: tas_mean, huss_mean, vas_mean, rsds_mean
	# Build hourly timeseries for representative year 2045 (non-leap)
	year = 2045
	start = datetime(year, 1, 1, 0)
	end = datetime(year + 1, 1, 1, 0)
	hours = int((end - start).total_seconds() // 3600)
	idx = pd.date_range(start, periods=hours, freq="H")

	# Map each timestamp to its month
	months = idx.month

	tas = zone_df.set_index('month')['tas_mean']
	huss = zone_df.set_index('month')['huss_mean']
	vas = zone_df.set_index('month')['vas_mean']
	rsds = zone_df.set_index('month')['rsds_mean']

	# Base values per hour = monthly mean
	T_base = months.map(tas).to_numpy()
	Q_base = months.map(huss).to_numpy()
	V_base = np.abs(months.map(vas).to_numpy())
	S_base = months.map(rsds).to_numpy()

	# Add simple diurnal cycle to temperature: sine wave +/-3C (scaled by month variability)
	hour_of_day = idx.hour.to_numpy()
	diurnal = 3.0 * np.sin((hour_of_day - 6) / 24.0 * np.pi)  # peak ~14-15h
	T = T_base + diurnal

	# Dew point from specific humidity
	Td = specific_humidity_to_dewpoint(Q_base)

	# Wind speed: use V_base (m/s) with small random variation
	np.random.seed(0)
	Wind = V_base * (0.8 + 0.4 * np.random.rand(len(V_base)))

	# Solar: distribute monthly mean S_base across daylight hours (6-18) with sinus shape
	S = np.zeros_like(S_base)
	for m in range(1, 13):
		mask = months == m
		# create daily pattern for 24h: zero night, sine during day
		daily_pattern = np.zeros(24)
		day_hours = np.arange(6, 19)
		daily_pattern[day_hours] = np.sin(np.linspace(0, np.pi, len(day_hours)))
		# scale pattern so hourly average over month equals monthly mean
		mean_pattern = daily_pattern.mean()
		if mean_pattern > 0:
			scale = months.map(rsds).to_numpy()[mask][0] / mean_pattern
			S[mask] = daily_pattern[hour_of_day[mask]] * scale
		else:
			S[mask] = 0.0

	# Assemble dataframe with needed EPW fields (we'll fill other columns with defaults)
	df = pd.DataFrame(index=idx)
	df['year'] = idx.year
	df['month'] = idx.month
	df['day'] = idx.day
	df['hour'] = idx.hour + 1  # EPW uses hours 1..24
	df['minute'] = 60
	df['drybulb_C'] = T
	df['dewpoint_C'] = Td
	# relative humidity placeholder
	df['relhum_%'] = np.nan
	df['atmos_Pa'] = 101325.0
	df['ghi_Wm2'] = S
	df['dirn_Wm2'] = 0.0
	df['dif_Wm2'] = 0.0
	df['wind_speed_m_s'] = Wind
	df['wind_dir_deg'] = 180.0

	return df


def write_epw(zone_name, df, outpath: Path):
	outpath.parent.mkdir(parents=True, exist_ok=True)
	with outpath.open('w', encoding='utf8', newline='') as f:
		# Minimal EPW header (9 lines). Many fields are placeholders.
		f.write(f"LOCATION,{zone_name},,,,,,,0,0,0,0,0\n")
		f.write("DESIGN CONDITIONS,0\n")
		f.write("TYPICAL/EXTREME PERIODS,0\n")
		f.write("GROUND TEMPERATURES,0\n")
		f.write("HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0\n")
		f.write("COMMENTS 1,Generated by epw_file_generator.py\n")
		f.write("COMMENTS 2,Representative future (2040-2069) monthly climatology\n")
		f.write("DATA PERIODS,1,1,Data,Sunday,01/01/2045,12/31/2045,1/1\n")
		# Column headers not required but useful
		f.write("Year,Month,Day,Hour,Minute,Source,DryBulbC,DewPointC,RelHum,AtmPress,ExtraRadHor,ExtraRadNorm,GlobalHor,DirectNor,DiffuseHor,GloHorIllum,DirNormIllum,DifHorIllum,ZenithLuminance,WindDir,WindSpeed,TotSkyCover,OpaqueSkyCover,Visibility,CeilingHeight,PresWeatherObs,PresWeatherCodes,PrecipWater, AOD, SnowDepth, DaysSinceSnow, Albedo, LiquidPrecipDepth, LiquidPrecipQty\n")

		for ts, row in df.iterrows():
			vals = [
				int(row['year']), int(row['month']), int(row['day']), int(row['hour']), int(row['minute']),
				0,  # data source
				f"{row['drybulb_C']:.2f}",
				f"{row['dewpoint_C']:.2f}",
				"",  # rel hum
				f"{row['atmos_Pa']:.1f}",
				"", "",  # extra rad
				f"{row['ghi_Wm2']:.2f}",
				f"{row['dirn_Wm2']:.2f}",
				f"{row['dif_Wm2']:.2f}",
				"", "", "", "",
				f"{row['wind_dir_deg']:.1f}",
				f"{row['wind_speed_m_s']:.2f}",
				"", "", "", "", "", "", "", "", "", "", "", ""
			]
			f.write(','.join(map(str, vals)) + '\n')


def main():
	if not STATS.exists():
		print(f"Monthly climatology not found at {STATS}. Aborting.")
		return

	mc = pd.read_csv(STATS)
	zones = mc['zone'].unique()
	OUTDIR.mkdir(parents=True, exist_ok=True)

	for zone in zones:
		zdf = mc[mc['zone'] == zone][['month', 'tas_mean', 'huss_mean', 'vas_mean', 'rsds_mean']].copy()
		if zdf['tas_mean'].isna().all():
			print(f"Skipping zone '{zone}' (no data)")
			continue
		zdf.columns = ['month', 'tas_mean', 'huss_mean', 'vas_mean', 'rsds_mean']
		df_hourly = make_hourly_series_for_zone(zdf)
		outpath = OUTDIR / f"{zone.replace(' ', '_')}_future_2040_2069.epw"
		print(f"Writing EPW for zone {zone} -> {outpath}")
		write_epw(zone, df_hourly, outpath)


if __name__ == '__main__':
	main()

